export const CRUD_CONFIG_SERVICE = 'CRUD_CONFIG_SERVICE';
export const AUTO_CRUD_RESOLVER_KEY = 'AUTO_CRUD_RESOLVER_KEY';
export const AUTO_CRUD_WRAP_RESOLVER_KEY = 'AUTO_CRUD_WRAP_RESOLVER_KEY';
export const AUTOCRUD_OPTIONS = 'AUTOCRUD_OPTIONS';
